New: ItemExtendedCost.dbc and ItemPurchaseGroup.dbc, Updated npc_vendor#extendedcost
azerothcore/wiki pull request #1017
Opened 2024-11-05 16:43 UTC by TheSCREWEDSoftware

### Description

- Created `ItemExtendedCost.dbc` (`itemextendedcost_dbc`)
- Updated `npc_vendor#extendedcost` to have proper link to the new`itemextendedcost_dbc`
- Created `ItemPurchaseGroup.dbc` (`itempurchasegroup_dbc`)

### Related Issue

Not aware

@pangolp new changes to the EN files

2024-11-05 18:18 UTC, Helias approved these changes

2024-11-14 19:36 UTC, Kitzunu commented on docs/itempurchasegroup_dbc.md
> +| [ItemID_1](#itemid_1)             | INT     | UNSIGNED   |     | NO   | 0       |
samne as other pr

2024-11-14 19:48 UTC, TheSCREWEDSoftware commented
Corrected

2024-11-18 14:11 UTC, TheSCREWEDSoftware commented
Ready to be reviewed.

2024-11-24 10:02 UTC, Kitzunu requested changes

2024-11-24 10:02 UTC, Kitzunu commented on docs/itemextendedcost_dbc.md
> +### DBC File Content
no

2024-11-24 10:02 UTC, Kitzunu commented on docs/itempurchasegroup_dbc.md
> +</details>
why

2024-11-24 11:15 UTC, TheSCREWEDSoftware commented on docs/itemextendedcost_dbc.md
> +### DBC File Content
Done

2024-11-24 11:15 UTC, TheSCREWEDSoftware commented on docs/itempurchasegroup_dbc.md
> +</details>
Done

2024-11-28 18:40 UTC, merged