chore(spell_custom_attr): add undocumented attr
azerothcore/wiki pull request #401
Opened 2021-02-14 11:25 UTC by Kitzunu

2021-02-14 11:52 UTC, Helias requested changes

2021-02-14 11:52 UTC, Helias commented on docs/spell_custom_attr.md
> +    SPELL_ATTR0_CU_NONE3                          = 128,
@SPELL_ATTR0_CU_NONE3 ?

2021-02-14 11:58 UTC, Kitzunu commented on docs/spell_custom_attr.md
> +    SPELL_ATTR0_CU_NONE3                          = 128,
Just adding the placeholders

2021-03-28 11:07 UTC, Kitzunu commented
Anyone? 😢

2021-03-28 11:14 UTC, FrancescoBorzi approved these changes

2021-03-28 11:15 UTC, merged