Update of changes in the structure of the account table
azerothcore/wiki pull request #569
Opened 2021-07-03 15:27 UTC by Tony931023

## Description
Update of changes in the structure of the account table

2021-07-03 18:05 UTC, FrancescoBorzi approved these changes

2021-07-03 19:48 UTC, Kitzunu requested changes

2021-07-03 19:48 UTC, Kitzunu commented on docs/account.md
> +| [id][1]               | INT(10)       | UNSIGNED   | PRI | NO   |                   | AUTO_INCREMENT | Identifier |
No. Remove yhe width from integers.

2021-07-03 23:36 UTC, Tony931023 commented
@Kitzunu full update, awaiting approval [https://github.com/azerothcore/wiki/pull/569/commits/4ae9c9047af685bea1f38d121fe5d7987cb2d3fe](url)

2021-07-04 09:04 UTC, Tony931023 commented
### I close them to accommodate the PR well, (Beginner's mistake)

2021-07-04 09:04 UTC, closed without merging