add multiple languages to sidebar with javascript
azerothcore/wiki pull request #597
Opened 2021-07-17 07:25 UTC by Tony931023

**Add multiple languages to sidebar with javascript**

@Kitzunu check and test to see if in this way the wiki sidebar allows you to switch between languages, for the implementation of the pages in Spanish
### Locally tested and it works

2021-07-17 16:08 UTC, Helias commented on _includes/azerothcore/sidebar.html
> +    </script>
```suggestion
    <script>
	function changeLang(language)
	{
            document.getElementById('es').style.display = (language == 'español') ? 'inline' : 'none';
            document.getElementById('en').style.display = (language == 'en') ? 'inline' : 'none';
	}
    </script>
```

2021-07-17 16:08 UTC, Helias commented on _includes/azerothcore/sidebar.html
> +    <div id='language'>
```suggestion
    <div id="language">
```

2021-07-17 16:09 UTC, Helias commented on _includes/azerothcore/sidebar.html
> +            <b style="cursor: pointer;" onclick="cambiar_a('en');"><img src="https://github.com/azerothcore/wiki/blob/test/images/gb.png" alt="Ingles"></b>
```suggestion
            <b style="cursor: pointer;" OnClick="changeLang('español');"><img src="https://github.com/azerothcore/wiki/blob/test/images/es.png" alt="Español"></b>
            <b style="cursor: pointer;" OnClick="changeLang('en');"><img src="https://github.com/azerothcore/wiki/blob/test/images/gb.png" alt="Ingles"></b>
```

2021-07-17 16:10 UTC, Helias commented
Not sure if this is the best way to change language, I would prefer to keep in a JSON dictionary all the keywords en/es and change only an index to change the language, so reduce the redundant code

2021-07-17 22:18 UTC, Tony931023 commented
@Helias  with JSON it would be a good idea, actually I would not know how to implement it like that, you have to add the libraries of https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js, I think javascript it is faster in this case.

The Wiki would look like this for the language change in the sidebar only, and in the other pages it would be something like @Kitzunu  did on the home page.

**In Spanish**

![es](https://user-images.githubusercontent.com/4868094/126050324-d5c43185-0b66-4300-90a8-fbdd8d8da04a.PNG)

**in English**
![in](https://user-images.githubusercontent.com/4868094/126050325-91c23068-3e1d-4ad4-b85c-89df48e13b58.PNG)

2021-07-17 22:48 UTC, Kitzunu requested changes
Is there a way to split the English/Spanish versions into 2 separate files and importing them into this one?

2021-07-17 22:48 UTC, Kitzunu commented on _includes/azerothcore/sidebar.html
> +            document.getElementById('en').style.display= (lenguaje=='en')? 'inline' : 'none';
```suggestion
	function changeLang(language)
        {
            document.getElementById('en').style.display= (language=='en')? 'inline' : 'none';
            document.getElementById('es').style.display= (language=='es')? 'inline' : 'none';
```

2021-07-17 22:48 UTC, Kitzunu commented on _includes/azerothcore/sidebar.html
> +            <b style="cursor: pointer;" onclick="changeLang('en');"><img src="https://github.com/azerothcore/wiki/blob/acbf3f05e90da007939ae32c8e9ec940f2e622ec/images/gb.png?raw=true"" alt="Ingles"><
```suggestion
            <b style="cursor: pointer;" onclick="changeLang('en');"><img src="https://github.com/azerothcore/wiki/blob/acbf3f05e90da007939ae32c8e9ec940f2e622ec/images/gb.png?raw=true" alt="English"></b>
            <b style="cursor: pointer;" onclick="changeLang('es');"><img src="https://github.com/azerothcore/wiki/blob/acbf3f05e90da007939ae32c8e9ec940f2e622ec/images/es.png?raw=true" alt="Spanish"></b>
```

2021-07-17 22:48 UTC, Kitzunu commented on _includes/azerothcore/sidebar.html
> +        <b>How-To ( branch master )</b> <a href="https://github.com/azerothcore/wiki/edit/master/_includes/azerothcore/sidebar.html">Edit</a>
put english at top

2021-07-17 23:56 UTC, Kitzunu commented
Is there a way to split the English/Spanish versions into 2 separate files and importing them into this one?

2021-07-18 00:10 UTC, Tony931023 commented
Maybe if the sidebar shows what is inside the <div class = "sidebar-wrapper"> tags, maybe doing something with JSON as a structure that will show the content according to the user's language. or to call another page and enclose it inside the sidebar with a structure.

  **I do not know if I explained well but more or less it is an idea**

2021-07-18 00:25 UTC, Kitzunu commented
I dont know web stuff well enough. All I thought of was if all the data could be separated, otherwise that file will be big as fuck

2021-07-18 02:35 UTC, Tony931023 commented
I do not think that for now this is the solution that I find most viable to translate the sidebar, also I do not think that for now another language other than Spanish is implemented in the wiki

2021-07-18 12:56 UTC, Kitzunu commented
Did you test the changes again after updating the names?

2021-07-18 21:09 UTC, Tony931023 commented
> 
> 
> Did you test the changes again after updating the names?

yes

2021-07-19 00:13 UTC, merged