vsc manual
azerothcore/wiki pull request #615
Opened 2021-07-30 15:53 UTC by Krejza9

### Description
Add manuals for  visual studio code
### Related Issue

Closes

2021-07-30 18:25 UTC, Tony931023 requested changes

2021-07-30 20:36 UTC, Krejza9 commented on docs/vsc_requirements.md
> +
done

2021-07-30 20:36 UTC, Krejza9 commented on docs/vsc_requirements.md
> +
done

2021-07-30 20:39 UTC, Krejza9 commented on docs/windows-vsc-core-installation.md
> +
done

2021-07-30 21:17 UTC, Kitzunu commented
I will look at this when I get time in the weekend.

2021-08-01 14:48 UTC, Kitzunu commented
I'll have to review this at a later date wont have time this weekend

2022-05-05 20:10 UTC, merged