Add link to triaging guide to the sidebar
azerothcore/wiki pull request #616
Opened 2021-08-02 00:43 UTC by Azcobu

### Description
Adds a link to the bug triaging guide to the wiki sidebar under the 'Contribute' heading.

2021-08-03 19:27 UTC, Tony931023 requested changes

2021-08-03 19:27 UTC, Tony931023 commented on _includes/azerothcore/sidebar.html
add on line 108


```suggestion
       <li><a href="/wiki/es/guide-to-triaging">Guía para la evaluación de errores</a></li> 
```

 for the Spanish translation

2021-08-04 08:25 UTC, Tony931023 approved these changes

2021-08-04 12:35 UTC, Helias approved these changes

2021-08-04 12:35 UTC, merged