Added build instructions for FreeBSD
azerothcore/wiki pull request #658
Opened 2021-12-08 14:19 UTC by SamuelGogarty

Adds documentation on how to build and install Azerothcore on FreeBSD

### Description
Covers how a user can install Azerothcore on FreeBSD, covers installation of build and runtime depend's, cmake configuration and compilation and installation of the project.
### Related Issue
https://github.com/azerothcore/azerothcore-wotlk/pull/9568

2021-12-08 14:20 UTC, SamuelGogarty commented
@Kitzunu can you please review this? thanks.
I would prefer if this was merged in only after https://github.com/azerothcore/azerothcore-wotlk/pull/9568 is merged.

2021-12-09 14:02 UTC, Kitzunu requested changes

2021-12-09 14:02 UTC, Kitzunu commented on docs/FreeBSD.md
> +# FreeBSD Install
keep file names only lower case.

the first header should match the file name. (The header can be capitalized as wished)

2021-12-09 14:02 UTC, Kitzunu commented on docs/FreeBSD.md
> +
```suggestion
```

2021-12-09 14:21 UTC, Kitzunu commented on docs/FreeBSD.md
> +# FreeBSD Install
https://www.azerothcore.org/wiki/wiki-standards

2021-12-10 15:53 UTC, SamuelGogarty commented
@Kitzunu file renamed and extra whitespace removed

2021-12-11 08:10 UTC, Kitzunu commented on docs/freebsd.md
> +# FreeBSD Install
the first header should match the file name. (The header can be capitalized as wished)

2021-12-11 18:42 UTC, SamuelGogarty commented
@Kitzunu removed 'Install' from header to conform to standards

2021-12-12 12:32 UTC, Helias approved these changes

2021-12-12 16:31 UTC, Kitzunu approved these changes

2021-12-12 16:32 UTC, merged