(EN) Added required file for OpenSSL 3.0
azerothcore/wiki pull request #849
Opened 2022-12-29 16:01 UTC by FiftyTifty

Added required file entry: libcrypto-3-x64.dll (Only for OpenSSL 3.0 and later)

### Description

- With OpenSSL 3.0, we need to also copy over the **libcrypto-3-x64.dll** file, not **just legacy.dll**
- The Spanish page differs from the English one, with it saying that OpenSLL 3.0 is not supported. I only know a few words of Spanish, so I can't rewrite it.

2022-12-29 17:28 UTC, heyitsbench commented
This `libcrypto-3-x64.dll` is not required to be in the directory to run the worldserver, at least not on my local.

2022-12-29 18:00 UTC, FiftyTifty commented
> This `libcrypto-3-x64.dll` is not required to be in the directory to run the worldserver, at least not on my local.

When I run Authserver without it, it throws the exception saying that it cannot be found, then crashes.

2022-12-29 21:03 UTC, Kitzunu commented
![image](https://user-images.githubusercontent.com/24550914/210010892-1e2acac1-3e5b-43b1-941d-83213fd8f986.png)

This is all you need.

Post the error message, please. And your setup in CMake

2022-12-29 21:04 UTC, Kitzunu requested changes
.

2022-12-30 00:13 UTC, FiftyTifty commented
> .
Yep no worries.

![error](https://user-images.githubusercontent.com/13511114/210022838-4f326b2b-fdab-4037-a6a6-b2dbd0349cdc.jpg)

![cmake](https://user-images.githubusercontent.com/13511114/210022856-5c7da3ca-a228-4deb-bb16-e067ebfa7490.jpg)

You are using the older OpenSSL version. To use OpenSSL 3, you need to copy over **legacy.dll** instead as per the wiki. But AuthServer will also throw the attached error, unless the other .dll is there as well.

2022-12-30 00:46 UTC, heyitsbench commented
For reference, [my CMake setup](https://user-images.githubusercontent.com/38561765/210024117-36a81311-9655-465d-b853-87aa8ee75a7f.png) along with [log](https://user-images.githubusercontent.com/38561765/210024134-18d14a7a-6ca3-4a9a-836e-572a783230ee.png). Once again, my local does not need this libcrypto file copied when using OpenSSL 3.0, only `legacy.dll`.

2022-12-30 20:02 UTC, Kitzunu commented
legacy not needed

2022-12-30 20:02 UTC, Kitzunu commented
@FiftyTifty search SSL in CMake and send a screenshot of that

2022-12-30 20:20 UTC, heyitsbench commented
> legacy not needed

![image](https://user-images.githubusercontent.com/38561765/210109077-840243f1-8142-4476-bcac-00e376713ae0.png)

2022-12-31 11:06 UTC, Kitzunu commented
kek

2023-01-03 17:17 UTC, FiftyTifty commented
> @FiftyTifty search SSL in CMake and send a screenshot of that

Sorry for the late reply. Life stuff.

![image](https://user-images.githubusercontent.com/13511114/210407873-1574458a-ea1c-494e-bf35-b610501dccff.png)

2023-04-01 15:44 UTC, closed without merging

2023-04-01 15:44 UTC, Kitzunu commented
Thank you